project:
  type: website

website:
  title: "WB1630-20 Statica"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sv.qmd
        text: Samenvatting

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



