project:
  type: website
  output-dir: docs

website:
  title: "WB1630-20 Statica"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sv.qmd
        text: Samenvatting
      - href: form.qmd
        text: Formulebladen

format:
  html: default



